service: lambda-ec2-ssh

frameworkVersion: '3'

provider:
  profile: iamadmin
  name: aws
  runtime: nodejs14.x
  iam:
    role:
        statements:
        managedPolicies:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

functions:
  ssh:
    handler: index.handler
    url: true

plugins:
  - serverless-offline    